services:
  c1:
    build:
      context: ./c1
      args:
        UBUNTU_VERSION: "16.04"
    container_name: C1
    tty: true
    stdin_open: true
    networks:
      - ssh_net

  c2:
    build:
      context: ./c2
      args:
        UBUNTU_VERSION: "18.04"
    container_name: C2
    tty: true
    stdin_open: true
    networks:
      - ssh_net

  c3:
    build:
      context: ./c3
      args:
        UBUNTU_VERSION: "20.04"
    container_name: C3
    tty: true
    stdin_open: true
    networks:
      - ssh_net

  c4:
    build:
      context: ./c4_s1
      args:
        UBUNTU_VERSION: "22.04"
    container_name: C4
    tty: true
    stdin_open: true
    networks:
      - ssh_net

  s1:
    build:
      context: ./c4_s1
      args:
        UBUNTU_VERSION: "22.04"
    container_name: S1
    hostname: s1
    ports:
      - "2222:22"
    tty: true
    stdin_open: true
    command: >
      bash -c "apt-get update && \
               apt-get install -y openssh-server && \
               id -u prueba &>/dev/null || useradd -m -s /bin/bash prueba && \
               echo 'prueba:prueba' | chpasswd && \
               mkdir -p /run/sshd && \
               /usr/sbin/sshd -D"
    networks:
      - ssh_net

networks:
  ssh_net:
    driver: bridge

